language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run test:coverage
  - codecov